//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpojTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tip { get; set; }
        public Nullable<int> Vodik { get; set; }
        public Nullable<int> Dusik { get; set; }
        public Nullable<int> Ugljik { get; set; }
        public Nullable<int> Natrij { get; set; }
        public Nullable<int> Kisik { get; set; }
    }
}
