//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpojTable
    {
        public int Id { get; set; }
        //public string Name { get; set; }
        //public string Tip { get; set; }
        //public Nullable<int> Vodik { get; set; }
        //public Nullable<int> Dusik { get; set; }
        //public Nullable<int> Ugljik { get; set; }
        //public Nullable<int> Natrij { get; set; }
        //public Nullable<int> Kisik { get; set; }
        [Required(ErrorMessage = "Unesite naziv spoja")]
        [Display(Name = "Naziv")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Unesite tip spoja")]
        [Display(Name = "Tip")]
        public string Tip { get; set; }
        [Display(Name = "Broj Vodika")]
        [Range(0, 999, ErrorMessage = "Vodik mora biti pozitivan broj")]
        public Nullable<int> Vodik { get; set; }
        [Display(Name = "Broj Dušik")]
        [Range(0, 999, ErrorMessage = "Dušik mora biti pozitivan broj")]
        public Nullable<int> Dusik { get; set; }
        [Display(Name = "Broj Ugljika")]
        [Range(0, 999, ErrorMessage = "Ugljik mora biti pozitivan broj")]
        public Nullable<int> Ugljik { get; set; }
        [Display(Name = "Broj Natrija")]
        [Range(0, 999, ErrorMessage = "Natrij mora biti pozitivan broj")]
        public Nullable<int> Natrij { get; set; }
        [Display(Name = "Broj Kisika")]
        [Range(0, 999, ErrorMessage = "Kisik mora biti pozitivan broj")]
        public Nullable<int> Kisik { get; set; }
        public string Error { get; set; }
    }
}
